spring:
  application:
    name: RoomieRadar
  datasource:
    url: jdbc:mysql://localhost:3306/roomieRadarData?createDatabaseIfNotExist=true
    username: root
    password: P@ssword
  jpa:
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
